# This is a basic workflow to help you get started with Actions

name: Synchronize OAS

on:
  schedule:
    # Run every day at 00:39 UTC
    - cron: '39 0 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  synchronize:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        api_name: [connector, distributor]
    concurrency:
      group: ${{ github.run_id }}

    steps:
      - name: Install oasdiff
        uses: jaxxstorm/action-install-gh-release@v1
        with: # Grab a specific tag with caching
          repo: Tufin/oasdiff
          tag: v1.10.27
          cache: enable
      - uses: actions/checkout@v4
      - name: Set env variables
        run: |
          echo "OAS_URL=https://api.mews.com/swagger/${{ matrix.api_name }}/swagger.yaml" >> $GITHUB_ENV
          echo "OUTPUT_OAS_FILE=${{ matrix.api_name }}/openapi.yaml" >> $GITHUB_ENV
          echo "OUTPUT_CHANGELOG_FILE=${{ matrix.api_name }}/CHANGELOG.md" >> $GITHUB_ENV
          echo "TMP_CHANGELOG_FILE=tmp/oasdiff-changelog.md" >> $GITHUB_ENV
          echo "TMP_OAS_FILE=tmp/${{ matrix.api_name }}.yaml" >> $GITHUB_ENV
          mkdir -p "${{ matrix.api_name }}"
          mkdir -p tmp
      - name: Download OAS
        run: |
          curl --no-progress-meter --create-dirs --output "$TMP_OAS_FILE" "$OAS_URL"
      
      - name: Run oasdiff and update changelog
        run: |
          ./scripts/changelog.sh
          mv -f "$TMP_OAS_FILE" "$OUTPUT_OAS_FILE"

      - uses: EndBug/add-and-commit@v9 # You can change this to use a specific version.
        with:
          # The arguments for the `git add` command (see the paragraph below for more info)
          # Default: '.'
          # add: 'src'

          # The local path to the directory where your repository is located. You should use actions/checkout first to set it up.
          # Default: '.'
          #cwd: './path/to/the/repo'

          # Determines the way the action fills missing author name and email. Three options are available:
          # - github_actor -> UserName <UserName@users.noreply.github.com>
          # - user_info -> Your Display Name <your-actual@email.com>
          # - github_actions -> github-actions <email associated with the github logo>
          # Default: github_actor
          default_author: github_actions

          # Arguments for the git fetch command. If set to false, the action won't fetch the repo.
          # For more info as to why fetching is usually recommended, please see the "Performance on large repos" FAQ.
          # Default: --tags --force
          #fetch: false

          pull: '--rebase --autostash'

          # The message for the commit.
          # Default: 'Commit from GitHub Actions (name of the workflow)'
          message: 'Synchronize OAS'
